version: '3.8'
services:
  postgres:
    image: 'postgres:12'
    container_name: todo-pg
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
    network_mode: bridge
    ports:
      - 5432:5432
    volumes:
      - todo_pg_data:/var/lib/postgresql/data


volumes:
  todo_pg_data:
    driver: local